---
title: "Adapt this title to indicate what you did"
author: "Student 1 name & Student 2 name"
date: '`r Sys.Date()`'
output:
  html_document:
    fig_caption: yes
    highlight: zenburn
    theme: cerulean
    toc: yes
    toc_depth: 3
  pdf_document:
    fig_caption: yes
    highlight: zenburn
    toc: yes
    toc_depth: 3
  word_document: default
---

## Introduction

- size: ~1/2 page
- context
- general motivation of the analysis
- particular questions/approaches addressed in this document



## Methods


~ 1/2 page + all details in supplementary material

- list of the resources and tools
- explanation of the main methodological choices



## Results

~ 2 pages, figures and tables non-included

* * * * * * 

## Conclusions/perspectives

~ 1/2 page, with summary of the results, some consideration about their relevance, and a perspective (what coul be done next ?)


* * * * * * 

## Supplementary material

An essential issue of scientific activity is  tractability (how were the results produced?) and reroducibility (can someone else reproduce the experiment, and get the same results?): the supmat must contain the precise list of all the commands / parameters used to achieve the results


### Data sources

A complete list of the data sources: provide the original IDs of the datasets (e.g. Gene Expression Omnibus GSE or GSM IDs, ArrayExpress IDs).

### Bioinformatics resources used for this work

The Table below indicates the bioinformatics resources (tools, databases) used for this analysis.

| Acronym | Description | URL | 
|---------|-------------|-----|
| RSAT | Regulatory Sequence Analysis Tools | <http://rsat.eu/> |
| ... | .... | ... Please complete the table ... |

### Complete list of commands and parameters

Please indicate here the complete list of tools, commands and parameters used to produce the results. In principle this should enable anyone to reproduce your analysis.

* * * * * * *
